id = "gossamer"
name = "Gossamer"
version = "0.11.1"
schema_version = 1
authors = ["Jason Abbott"]
description = "Modern, pure CSS language intelligence powered by go-css-lsp"
repository = "https://github.com/toba/gossamer"

[language_servers.gossamer]
name = "Gossamer"
languages = ["CSS"]

[language_servers.gossamer.language_ids]
"CSS" = "css"
